---
title: "Untitled"
author: "Daniel Jensen"
date: "2024-02-16"
output: html_document
---


```{r}
library(tidyverse)
```

```{r}
header.true <- function(df) {
  names(df) <- as.character(unlist(df[1,]))
  df[-1,]
}
```

```{r}
data <-  data[,-1]
```


```{r}
# List all TSV files in the directory
setwd("C:\\Users\\dwarf\\Dataproject\\data_normalized_split\\2mers_extend200")
tsv_files <- list.files(pattern = "\\.tsv$")

# Sort the list of TSV files
#tsv_files <- sort(tsv_files)

# Initialize an empty list to store data frames
data_list <- list()

# Loop through each TSV file, read it, and store it in the list
for (file in tsv_files) {
  data <- read_tsv(file, show_col_types = FALSE)
  data <- as.data.frame(t(data))
  data <- header.true(data)
  data <- data[,-1]
  data_list[[file]] <- data
}

# Combine all data frames into a single data frame
combined_2mers <- do.call(rbind, data_list)

# List all TSV files in the directory
setwd("C:\\Users\\dwarf\\Dataproject\\data_normalized_split\\4mers_extend200")
tsv_files <- list.files(pattern = "\\.tsv$")

# Sort the list of TSV files
#tsv_files <- sort(tsv_files)

# Initialize an empty list to store data frames
data_list <- list()

# Loop through each TSV file, read it, and store it in the list
for (file in tsv_files) {
  data <- read_tsv(file, show_col_types = FALSE)
  data <- as.data.frame(t(data))
  data <- header.true(data)
  data <- data[,-1]
  data_list[[file]] <- data
}

# Combine all data frames into a single data frame
combined_4mers <- do.call(rbind, data_list)

# List all TSV files in the directory
setwd("C:\\Users\\dwarf\\Dataproject\\data_normalized_split\\6mers_extend200")
tsv_files <- list.files(pattern = "\\.tsv$")

# Sort the list of TSV files
#tsv_files <- sort(tsv_files)

# Initialize an empty list to store data frames
data_list <- list()

# Loop through each TSV file, read it, and store it in the list
for (file in tsv_files) {
  data <- read_tsv(file, show_col_types = FALSE)
  data <- as.data.frame(t(data))
  data <- header.true(data)
  data <- data[,-1]
  data_list[[file]] <- data
}

# Combine all data frames into a single data frame
combined_6mers <- do.call(rbind, data_list)



```
```{r}
#write_tsv(combined_2mers,"C:\\Users\\dwarf\\Dataproject\\data_combined_with_background\\combined_2mers_with_background.tsv")
#write_tsv(combined_4mers,"C:\\Users\\dwarf\\Dataproject\\data_combined_with_background\\combined_4mers_with_background.tsv")
#write_tsv(combined_6mers,"C:\\Users\\dwarf\\Dataproject\\data_combined_with_background\\combined_6mers_with_background.tsv")
```

```{r}
combined_2mers_meth_even <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_2mers_meth_even.tsv", col_select = 1:16)
combined_2mers_meth_odd <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_2mers_meth_odd.tsv", col_select = 1:16)
combined_2mers_unmeth_even <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_2mers_unmeth_even.tsv")
combined_2mers_unmeth_odd <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_2mers_unmeth_odd.tsv")
combined_4mers_meth_even <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_4mers_meth_even.tsv")
combined_4mers_meth_odd <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_4mers_meth_odd.tsv")
combined_4mers_unmeth_even <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_4mers_unmeth_even.tsv")
combined_4mers_unmeth_odd <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_4mers_unmeth_odd.tsv")
combined_6mers_meth_even <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_6mers_meth_even.tsv")
combined_6mers_meth_odd <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_6mers_meth_odd.tsv")
combined_6mers_unmeth_even <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_6mers_unmeth_even.tsv")
combined_6mers_unmeth_odd <- read_tsv("C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_6mers_unmeth_odd.tsv")



meta_data <- read_tsv("C:\\Users\\dwarf\\Dataproject\\ctDNA_frag_meth\\metadata.tsv", col_names = FALSE)
```
```{r}
combined_2mers_meth_even <- combined_2mers %>% slice(which(row_number()%% 4 == 1))
combined_2mers_meth_odd <- tail(combined_2mers,-1)
combined_2mers_meth_odd <- combined_2mers_meth_odd %>% slice(which(row_number()%% 4 == 1))
combined_2mers_unmeth_even <- tail(combined_2mers,-2)
combined_2mers_unmeth_even <- combined_2mers_unmeth_even %>% slice(which(row_number()%% 4 == 1))
combined_2mers_unmeth_odd <- tail(combined_2mers,-3)
combined_2mers_unmeth_odd <- combined_2mers_unmeth_odd %>% slice(which(row_number()%% 4 == 1))
```

```{r}
combined_4mers_meth_even <- combined_4mers %>% slice(which(row_number()%% 4 == 1))
combined_4mers_meth_odd <- tail(combined_4mers,-1)
combined_4mers_meth_odd <- combined_4mers_meth_odd %>% slice(which(row_number()%% 4 == 1))
combined_4mers_unmeth_even <- tail(combined_4mers,-2)
combined_4mers_unmeth_even <- combined_4mers_unmeth_even %>% slice(which(row_number()%% 4 == 1))
combined_4mers_unmeth_odd <- tail(combined_4mers,-3)
combined_4mers_unmeth_odd <- combined_4mers_unmeth_odd %>% slice(which(row_number()%% 4 == 1))
```
¨
```{r}
combined_6mers_meth_even <- combined_6mers %>% slice(which(row_number()%% 4 == 1))
combined_6mers_meth_odd <- tail(combined_6mers,-1)
combined_6mers_meth_odd <- combined_6mers_meth_odd %>% slice(which(row_number()%% 4 == 1))
combined_6mers_unmeth_even <- tail(combined_6mers,-2)
combined_6mers_unmeth_even <- combined_6mers_unmeth_even %>% slice(which(row_number()%% 4 == 1))
combined_6mers_unmeth_odd <- tail(combined_6mers,-3)
combined_6mers_unmeth_odd <- combined_6mers_unmeth_odd %>% slice(which(row_number()%% 4 == 1))
```



```{r}
combined_2mers_meth <- combined_2mers %>% slice(which(row_number()%% 2 == 1))
combined_2mers_unmeth <- tail(combined_2mers,-1)
combined_2mers_unmeth <- combined_2mers_unmeth %>% slice(which(row_number()%% 2 == 1))

```
```{r}
combined_4mers_meth <- combined_4mers %>% slice(which(row_number()%% 2 == 1))
combined_4mers_unmeth <- tail(combined_4mers,-1)
combined_4mers_unmeth <- combined_4mers_unmeth %>% slice(which(row_number()%% 2 == 1))

```
```{r}
combined_6mers_meth <- combined_6mers %>% slice(which(row_number()%% 2 == 1))
combined_6mers_unmeth <- tail(combined_6mers,-1)
combined_6mers_unmeth <- combined_6mers_unmeth %>% slice(which(row_number()%% 2 == 1))

```

```{r}
meta_data_fin <- rbind(c("background","background"),meta_data)
meta_data_sort <- meta_data_fin[order(meta_data_fin$X1),]
```

```{r}
combined_2mers_meth_even<- combined_2mers_meth_even %>% mutate("cancer" = meta_data_sort$X2)
combined_2mers_meth_odd<- combined_2mers_meth_odd %>% mutate("cancer" = meta_data_sort$X2)
combined_2mers_unmeth_even <- combined_2mers_unmeth_even %>% mutate("cancer" = meta_data_sort$X2)
combined_2mers_unmeth_odd <- combined_2mers_unmeth_odd %>% mutate("cancer" = meta_data_sort$X2)
combined_4mers_meth_even <- combined_4mers_meth_even %>% mutate("cancer" = meta_data_sort$X2)
combined_4mers_meth_odd <- combined_4mers_meth_odd %>% mutate("cancer" = meta_data_sort$X2)
combined_4mers_unmeth_even <- combined_4mers_unmeth_even %>% mutate("cancer" = meta_data_sort$X2)
combined_4mers_unmeth_odd <- combined_4mers_unmeth_odd %>% mutate("cancer" = meta_data_sort$X2)
combined_6mers_meth_even <- combined_6mers_meth_even %>% mutate("cancer" = meta_data_sort$X2)
combined_6mers_meth_odd <- combined_6mers_meth_odd %>% mutate("cancer" = meta_data_sort$X2)
combined_6mers_unmeth_even <- combined_6mers_unmeth_even %>% mutate("cancer" = meta_data_sort$X2)
combined_6mers_unmeth_odd <- combined_6mers_unmeth_odd %>% mutate("cancer" = meta_data_sort$X2)
```
```{r}
write_tsv(combined_2mers_meth_even,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_2mers_meth_even.tsv")
write_tsv(combined_2mers_meth_odd,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_2mers_meth_odd.tsv")

write_tsv(combined_2mers_unmeth_even,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_2mers_unmeth_even.tsv")
write_tsv(combined_2mers_unmeth_odd,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_2mers_unmeth_odd.tsv")

write_tsv(combined_4mers_meth_even,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_4mers_meth_even.tsv")
write_tsv(combined_4mers_meth_odd,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_4mers_meth_odd.tsv")

write_tsv(combined_4mers_unmeth_even,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_4mers_unmeth_even.tsv")
write_tsv(combined_4mers_unmeth_odd,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_4mers_unmeth_odd.tsv")

write_tsv(combined_6mers_meth_even,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_6mers_meth_even.tsv")

write_tsv(combined_6mers_meth_odd,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_6mers_meth_odd.tsv")

write_tsv(combined_6mers_unmeth_even,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_6mers_unmeth_even.tsv")
write_tsv(combined_6mers_unmeth_odd,"C:\\Users\\dwarf\\Dataproject\\data_combined_split\\combined_6mers_unmeth_odd.tsv")

```



```{r}
combined_2mers_meth_healthy <- filter(combined_2mers_meth, cancer =="Healthy")
combined_2mers_meth_cancer <- filter(combined_2mers_meth, cancer !="Healthy")
combined_2mers_unmeth_healthy <- filter(combined_2mers_unmeth, cancer =="Healthy")
combined_2mers_unmeth_cancer <- filter(combined_2mers_unmeth, cancer !="Healthy")
combined_4mers_meth_healthy <- filter(combined_4mers_meth, cancer =="Healthy")
combined_4mers_meth_cancer <- filter(combined_4mers_meth, cancer !="Healthy")
combined_4mers_unmeth_healthy <- filter(combined_4mers_unmeth, cancer =="Healthy")
combined_4mers_unmeth_cancer <- filter(combined_4mers_unmeth, cancer !="Healthy")
combined_6mers_meth_healthy <- filter(combined_6mers_meth, cancer =="Healthy")
combined_6mers_meth_cancer <- filter(combined_6mers_meth, cancer !="Healthy")
combined_6mers_unmeth_healthy <- filter(combined_6mers_unmeth, cancer =="Healthy")
combined_6mers_unmeth_cancer <- filter(combined_6mers_unmeth, cancer !="Healthy")
combined_2mers_healthy <- filter(combined_2mers, cancer =="Healthy")
combined_2mers_cancer <- filter(combined_2mers, cancer !="Healthy")
combined_4mers_healthy <- filter(combined_4mers, cancer =="Healthy")
combined_4mers_cancer <- filter(combined_4mers, cancer !="Healthy")
combined_6mers_healthy <- filter(combined_6mers, cancer =="Healthy")
combined_6mers_cancer <- filter(combined_6mers, cancer !="Healthy")
```

